#!/usr/bin/env python

import rospy
from road_detect.road_detect import RoadDetect


if __name__ == '__main__':
	rospy.init_node('road_detect', anonymous=True)
	rd = RoadDetect()

	try:
		rospy.spin()
	except KeyboardInterrupt:
		print("Shutting down")